name: Unit Tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**.py"

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: true
      - name: Install dependencies
        run: uv pip install -r requirements.txt
      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py') --rcfile=.pylintrc
      - name: Unit tests
        run: uv run -m main.test
